name: Check for __init__.py files

on: 
  push:
      branches:
        - miruuna/fix-broken-pages


jobs:
  check-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify __init__.py presence
        run: |
          missing=$(find src -mindepth 1 -type d \
            -not -path "./.git*" \
            -not -path "./.github*" \
            -not -path "./tests*" \
            -not -path "./docs*" \
            -not -path "./config*" \
            -not -path "./drunc/data*" \
            -exec sh -c '[ ! -e "$1/__init__.py" ] && echo "$1"' _ {} \;)

          if [ -n "$missing" ]; then
            echo "❌ The following directories are missing __init__.py:"
            echo "$missing"
            exit 1
          else
            echo "✅ All applicable directories contain __init__.py"
          fi
